### ISSUE TITLE
Update docs to reflect new tag naming

### ISSUE THREAD

**Issue by dogweather** [scrapinghub/scrapinghub-stack-scrapy#144]
It appears that with version **2.1**, you are no longer appending `py3`. I.e., they're Python 3 by default. (This is undocumented as far as I can tell. I'm inferring it from the Docker config.) This is great, if I'm correct.

However, the docs don't reflect this, and I spent a lot of time chasing them around. Could you please update these?

* https://support.scrapinghub.com/support/solutions/articles/22000200387-deploying-python-3-spiders-to-scrapy-cloud
* https://support.scrapinghub.com/support/solutions/articles/22000200402
* https://github.com/scrapinghub/scrapinghub-stack-scrapy#branches-and-tags

**Comment by vshlapakov** [comment]
Addressed by https://github.com/scrapinghub/scrapinghub-stack-scrapy/pull/147.

**Comment by dogweather** [comment]
Thank you!
