### ISSUE TITLE
{"message": "manifest for scrapinghub/scrapinghub-stack-scrapy:2.3-py3 not found"}, "error": "build_error"}

### ISSUE THREAD

**Issue by daynetran** [scrapinghub/scrapinghub-stack-scrapy#146]
`stacks:
     default: scrapy:2.3-py3
`
gives me the above error when I try to deploy my Scrapy project. 
The latest scrapy:xx that works is 1.8. Is this something that can be resolved?

**Comment by vshlapakov** [comment]
All recent stacks starting from `2.0` already comes with Python 3, so you should use `scrapy:2.3` one instead.
