### ISSUE TITLE
Update README.rst file

### ISSUE THREAD

**Issue by phrfpeixoto** [scrapinghub/scrapinghub-stack-scrapy#148]
The project's README.rst file needs to be reviewed/updated.

IE:

> Note: Lack of -py3 suffix means that a stack is built using Python 2.

That is no longer true since version 2.0, where support for Python 2 was dropped.

**Comment by vshlapakov** [comment]
Addressed by https://github.com/scrapinghub/scrapinghub-stack-scrapy/pull/149, thanks!
