### ISSUE TITLE
Zyte/SH stack for scrapy 2.5

### ISSUE THREAD

**Issue by DharmeshPandav** [scrapinghub/scrapinghub-stack-scrapy#155]
Hi

I was in the process of using latest Scrapy 2.5 with Python 3.9 support but have to hold back as there is no Scrapy stack for 2.5 yet

I could not find any guidance on how long before We create a scrapy stack after Scrapy version is released

Scrapy 2.5 is released before 20 days on 2021-04-06 

I have checked tags on docker and see that generally Scrapy stack release is followed couple of days after Scrapy version release.

Thanks

**Comment by vshlapakov** [comment]
Thanks for pushing things forward and separately for the PR, it nicely improves and unifies the official release process. I took your changes as a base and updated it to comply with our workflow, should be addressed by https://github.com/scrapinghub/scrapinghub-stack-scrapy/pull/159, I'll release the new stack shortly.
