### ISSUE TITLE
scrapinghub-entrypoint-scrapy upgrade to 0.7.0

### ISSUE THREAD

**Issue by csalazar** [scrapinghub/scrapinghub-stack-scrapy#4]
Hi guys, I've used `scrapinghub/scrapinghub-stack-scrapy:1.1` as base image in a *DockerFile* and then testing with `shub-image test` says: 

```
Error: list-spiders command is not found in the image.
Please upgrade your scrapinghub-entrypoint-scrapy(>=0.7.0)
```

Is it possible to upgrade or there's some inconvenience?

**Comment by chekunkov** [comment]
Latest version is 0.8.1 [already](https://github.com/scrapinghub/scrapinghub-stack-scrapy/commit/2231ab6330bac98c6f191dc9185508f56aa7cc0d), closing this issue.
