### ISSUE TITLE
Regarding the `scrapylib` dependency and the Python 3 versions

### ISSUE THREAD

**Issue by starrify** [scrapinghub/scrapinghub-stack-scrapy#66]
It's been observed that the package `scrapylib` has been included as a dependency in the Python 3 versions. E.g. in the current version of `1.5-py3` there is `scrapylib==1.7.1` on [this line](https://github.com/scrapinghub/scrapinghub-stack-scrapy/blob/da4fbf79a1dbe795ea09f941c9de220a72a8d6c5/requirements.txt#L58)

However `scrapylib` hasn't been py3-compatible even at version 1.7.1. Its repository does contain some changes (like in [`f71f2e5`](https://github.com/scrapinghub/scrapylib/commit/f71f2e57ef8a19084d1cbe307f70d7053707cc07)) to resolve most of its compatibility issues, but such changes seem not to have been included in the latest version of 1.7.1.

Now as the `scrapylib` repository on GitHub has gone private, we may not reference its commit ID in the requirement files here.  
But it may look inappropriate to keep including it in the Python 3 versions.

Maybe we could talk to the `scrapylib` maintainers and see whether they could release a new version including the py3-compatible changes? Or any other solutions?

**Comment by vshlapakov** [comment]
Good point, thanks for sharing! Unfortunately we can't just drop `scrapylib` from existing stacks, because some projects can rely on it (use its parts compatible with py3 or just have imports). But we can (and should) safely drop `scrapylib` in future stacks (i.e. `1.6*` unreleased yet).

It's also not clear why `scrapylib` has gone private, deprecation is a bad reason for it. сс @dangra

**Comment by dangra** [comment]
> It's also not clear why scrapylib has gone private, deprecation is a bad reason for it.

I think deprecation was the reason indeed. I made it public again but archived.

**Comment by vshlapakov** [comment]
Thanks @dangra. I'm going to keep this issue opened as a reminder to drop `scrapylib` in future stacks.

**Comment by vshlapakov** [comment]
Dropped `scrapylib` in the recent `scrapy:2.0` stack, let's finally close the issue.
