### ISSUE TITLE
RuntimeError: Pipe writer is misconfigured, named pipe path is not set

### ISSUE THREAD

**Issue by villeristi** [scrapinghub/scrapinghub-stack-scrapy#82]
Trying to build a custom docker-image with:
```
1. scrapy startproject test
2. scrapy genspider testSpider
3. shub image init
4. docker build . -t customnamehere
```
Dockerfile:

```
FROM scrapinghub/scrapinghub-stack-scrapy:1.5-py3
ENV TERM xterm
ENV SCRAPY_SETTINGS_MODULE test.settings
RUN mkdir -p /app
WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app
RUN python setup.py install
```

command `docker run customnamehere shub-image-info` works like it should but `docker run customnamehere start-crawl` 

throws 

```RuntimeError: Pipe writer is misconfigured, named pipe path is not set```

Is there some more steps to properly configure or...?

Not sure if this a bug in `scrapinghub-entrypoint-scrapy` or misconfiguration in this repo though.

**Comment by vshlapakov** [comment]
Replied in https://github.com/scrapinghub/scrapinghub-entrypoint-scrapy/issues/52, it's not about a bug or misconfiguration but rather about a feature request that we're going to address a bit later.
